server:
  port: 8190
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: Redis@dhcc123.com
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hanjiang-etm?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root123123
    # 初始连接数
    initial-size: 5
    # 最小连接池数量
    min-idle: 10
    # 最大连接池数量
    max-active: 20
    # 最大等待时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    max-evictable-idle-time-millis: 900000
    # 检查连接是否有效
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat,wall

# mybatis-plus配置
mybatis-plus:
  configuration:
    # SQL日志设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 驼峰命名
    map-underscore-to-camel-case: true

# 日志级别
logging:
  level:
    com.hanjiang.etm: debug # off
